### ISSUE TITLE
Missing step in setting up bcrypt 

### ISSUE THREAD

**Issue by gerbyzation** [realpython/test-driven#2]
I've been following along through the tutorials and unless I'm missing something a step is missing in Part 3 Flask Bcrypt. The tutorial installs `flask-bcrypt`, initialises the extension in `project/__init__.py`. It goes on to update some bits of code to setup a user password as well, but when it is mentioned that the tests run slower because of the `BCRYPT_LOG_ROUNDS`, I could initially not notice a difference and no code has been added to actually hash the password? 

Looking at the flask-microservice-users repo with the finished code, it has added a call to `bcrypt.generate_password_hash` in the constructor method of the User model, as to make the following: 
```python
def __init__(self, username, email, password, created_at=datetime.datetime.utcnow()):
        self.username = username
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, current_app.config.get('BCRYPT_LOG_ROUNDS')
        ).decode()
        self.created_at = created_at
```
I added this code to my User model and that made my tests pass and also result in slower tests due to the log rounds.

**Comment by mjhea0** [comment]
Nice catch! I just updated the lesson. Look good?
